package com.dnd.dicelobby.models

data class Feat(
    val name: String,
    val prerequisite: String = "",
    val description: String
)

val DND_FEATS: List<Feat> = listOf(
    // ── PHB Feats ─────────────────────────────────────────────────────────────
    Feat("Alert",
        description = "+5 to initiative. Can't be surprised while conscious. Creatures you haven't seen don't gain advantage on attack rolls against you."),
    Feat("Athlete",
        description = "STR or DEX +1. Standing from prone costs only 5 ft. Climbing costs no extra movement. Running long/high jump requires only 5 ft run-up."),
    Feat("Actor",
        description = "CHA +1. Advantage on Deception and Performance checks when impersonating a creature. Can mimic the speech of a person or sounds of creatures you have heard."),
    Feat("Charger",
        description = "When you Dash and then attack the same turn, bonus action grants +5 damage on a weapon attack or pushes the target 10 ft."),
    Feat("Crossbow Expert",
        description = "Ignore loading property of crossbows. No disadvantage for ranged attacks within 5 ft. Bonus action attack with hand crossbow when using a one-handed weapon."),
    Feat("Defensive Duelist", "DEX 13",
        description = "When holding a finesse weapon and a creature hits you, use your reaction to add your proficiency bonus to AC for that attack."),
    Feat("Dual Wielder",
        description = "AC +1 when wielding two melee weapons. Can use two-weapon fighting with non-light weapons. Can draw or stow two weapons at once."),
    Feat("Dungeon Delver",
        description = "Advantage on Perception and Investigation checks to detect secret doors. Advantage on saves against traps. Resistance to trap damage. Can search for traps at normal pace."),
    Feat("Durable", "CON 13",
        description = "CON +1. Minimum hit points regained on short rest die equals twice your CON modifier (minimum 2)."),
    Feat("Elemental Adept", "Spellcasting feature",
        description = "Choose acid, cold, fire, lightning, or thunder. Spells of that damage type ignore resistance. When rolling for that type, treat any 1 as a 2."),
    Feat("Grappler", "STR 13",
        description = "Advantage on attack rolls against creatures you are grappling. Can pin a grappled creature (both become restrained) with an action."),
    Feat("Great Weapon Master",
        description = "When you score a crit or reduce a creature to 0 HP with a heavy melee weapon, bonus action attack. Take -5 to hit for +10 damage with a heavy melee weapon."),
    Feat("Healer",
        description = "Use a healer's kit as an action to stabilize a creature (no Medicine check). Use a healer's kit to restore 1d6 + 4 + creature's max HD HP (once per short rest per creature)."),
    Feat("Heavily Armored", "Medium Armor proficiency",
        description = "STR +1. Gain proficiency with heavy armor."),
    Feat("Heavy Armor Master", "Heavy Armor proficiency",
        description = "STR +1. While wearing heavy armor, reduce non-magical bludgeoning, piercing, and slashing damage by 3."),
    Feat("Inspiring Leader", "CHA 13",
        description = "After a short rest, give an inspiring speech to up to 6 allies. Each gains temporary HP equal to your level + CHA modifier."),
    Feat("Keen Mind",
        description = "INT +1. Always know which direction is north. Know how many hours until the next sunrise/sunset. Can accurately recall anything seen or heard within the past month."),
    Feat("Lightly Armored",
        description = "STR or DEX +1. Gain proficiency with light armor."),
    Feat("Linguist",
        description = "INT +1. Learn 3 languages of your choice. Can create ciphers. Others need INT check (DC = INT score + proficiency bonus) to decode them."),
    Feat("Lucky",
        description = "Gain 3 luck points. When you make an attack, ability check, or saving throw, spend 1 point to roll an extra d20 and choose which result to use. Also use when attacked."),
    Feat("Mage Slayer",
        description = "When a creature within 5 ft casts a spell, use your reaction to make a melee attack against it. Creatures you damage this way have disadvantage on concentration checks. Advantage on saves against nearby spellcasters."),
    Feat("Magic Initiate",
        description = "Choose bard, cleric, druid, sorcerer, warlock, or wizard. Learn 2 cantrips and one 1st-level spell from that class's list. Cast the 1st-level spell once per long rest."),
    Feat("Martial Adept",
        description = "Learn 2 maneuvers from the Battle Master archetype. Gain 1 superiority die (d6). These can be used with the maneuvers."),
    Feat("Medium Armor Master", "Medium Armor proficiency",
        description = "Wearing medium armor doesn't impose disadvantage on Stealth checks. DEX +3 to AC instead of +2 when wearing medium armor."),
    Feat("Mobile",
        description = "Speed increases by 10 ft. When you Dash, difficult terrain costs no extra movement. If you attack a creature, they can't make opportunity attacks against you for the rest of your turn."),
    Feat("Moderately Armored", "Light Armor proficiency",
        description = "STR or DEX +1. Gain proficiency with medium armor and shields."),
    Feat("Mounted Combatant",
        description = "Advantage on melee attacks against unmounted creatures smaller than your mount. Force attacks targeting your mount to target you instead. Your mount doesn't take half damage from saves; you take none on a success, half on a fail."),
    Feat("Observant",
        description = "INT or WIS +1. If you see a creature's mouth moving, can interpret what it's saying if you know its language. Passive Perception and Investigation +5."),
    Feat("Polearm Master",
        description = "Bonus action attack with the butt of a glaive, halberd, pike, or quarterstaff. Opportunity attacks when creatures enter your reach."),
    Feat("Resilient",
        description = "Choose one ability score. It increases by 1. Gain proficiency in saving throws using that ability."),
    Feat("Ritual Caster", "INT or WIS 13",
        description = "Acquire a ritual book. Choose a class: bard, cleric, druid, sorcerer, warlock, or wizard. Learn 2 ritual spells of 1st level from that class. Can copy more rituals into the book."),
    Feat("Savage Attacker",
        description = "Once per turn when rolling damage for a melee weapon attack, roll the damage dice twice and use the higher result."),
    Feat("Sentinel",
        description = "When you hit a creature making an opportunity attack, its speed drops to 0. Creatures within 5 ft can't Disengage. When a creature attacks an ally within 5 ft of you, use your reaction to make a melee attack."),
    Feat("Sharpshooter",
        description = "No disadvantage for long range. Ranged attacks ignore half and three-quarters cover. Take -5 to hit for +10 damage with a ranged weapon."),
    Feat("Shield Master",
        description = "If you attack on your turn, bonus action to shove. Add shield AC bonus to DEX saves against spells targeting only you. Take no damage on a successful DEX save if wielding a shield."),
    Feat("Skilled",
        description = "Gain proficiency in any combination of 3 skills or tools."),
    Feat("Skulker", "DEX 13",
        description = "Can hide when only lightly obscured. Missing a ranged attack while hidden doesn't reveal you. Dim light doesn't impose disadvantage on Perception checks relying on sight."),
    Feat("Spell Sniper", "Spellcasting feature",
        description = "Double the range of attack-roll spells. Those spells ignore half and three-quarters cover. Learn one attack-roll cantrip from any class."),
    Feat("Tavern Brawler",
        description = "STR or CON +1. Proficiency with improvised weapons and unarmed strikes (1d4 bludgeoning). When you hit with an improvised weapon or unarmed strike, bonus action to grapple."),
    Feat("Tough",
        description = "HP maximum increases by 2 for every level gained (past and future)."),
    Feat("War Caster", "Spellcasting feature",
        description = "Advantage on CON saves to maintain concentration. Can perform somatic components while holding weapons/shield. When a creature provokes an opportunity attack from you, cast a single-target spell instead."),
    Feat("Weapon Master",
        description = "STR or DEX +1. Gain proficiency with 4 weapons of your choice."),

    // ── Tasha's Cauldron / Xanathar's Feats ────────────────────────────────
    Feat("Artificer Initiate",
        description = "Learn 1 artificer cantrip. Learn 1 1st-level artificer spell, cast once per long rest. Gain proficiency with one type of artisan's tools."),
    Feat("Chef",
        description = "CON or WIS +1. Proficiency with cook's utensils. Short rest: prepare treats equal to CON modifier that each grant 1d8 temp HP. Long rest: cook special food that gives extra temp HP."),
    Feat("Crusher",
        description = "STR or CON +1. When you hit with a bludgeoning weapon, move the creature 5 ft. Once per turn when you score a crit, all attacks against that creature have advantage until your next turn."),
    Feat("Eldritch Adept", "Spellcasting feature",
        description = "Learn one Eldritch Invocation from the warlock list for which you meet the prerequisites."),
    Feat("Fey Touched",
        description = "INT, WIS, or CHA +1. Learn Misty Step and one 1st-level divination or enchantment spell. Both can be cast once per long rest, or using spell slots."),
    Feat("Fighting Initiate", "Proficiency with a martial weapon",
        description = "Learn one Fighting Style from the fighter list. You can replace the fighting style when you gain a level if you also have this feat from a class."),
    Feat("Metamagic Adept", "Spellcasting feature",
        description = "Learn 2 Metamagic options from the sorcerer class. Gain 2 sorcery points that can only be used for Metamagic, refreshing on a long rest."),
    Feat("Piercer",
        description = "STR or DEX +1. Once per turn when you score a hit with piercing damage, reroll one damage die and use the higher result. On a crit, roll an extra piercing damage die."),
    Feat("Poisoner",
        description = "Proficiency with poisoner's kit. Ignore resistance to poison damage. Coat a weapon with a potent poison as a bonus action; on a hit the target makes DC 14 CON save or takes 2d8 poison and is poisoned until the end of your next turn."),
    Feat("Shadow Touched",
        description = "INT, WIS, or CHA +1. Learn Invisibility and one 1st-level illusion or necromancy spell. Both can be cast once per long rest, or using spell slots."),
    Feat("Skill Expert",
        description = "INT +1 (or any ability). Gain proficiency in one skill. Gain expertise (double proficiency bonus) in one skill you are already proficient in."),
    Feat("Slasher",
        description = "STR or DEX +1. Once per turn when you hit with a slashing weapon, reduce the target's speed by 10 ft until the start of your next turn. On a crit, the target has disadvantage on attack rolls until the start of your next turn."),
    Feat("Telepathic",
        description = "INT, WIS, or CHA +1. Speak telepathically to a creature within 60 ft (that knows a language) as a bonus action. Cast Detect Thoughts once per long rest (using the relevant ability as the spellcasting ability)."),
    Feat("Telekinetic",
        description = "INT, WIS, or CHA +1. Learn Mage Hand or improve its range and invisibility. As a bonus action, telekinetically shove a creature within 30 ft: 5 ft push or pull on a failed STR save (DC 8 + proficiency + relevant modifier).")
)
